name: Deploy static content to Pages

on:
  push:
    branches:
      - main  # Set a branch name to deploy
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Deploy
        run: |
          mkdir -p public
          cp school_enrollment_map.html public/
          touch public/.nojekyll
          echo "school-enrollment-map" > public/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy-page:
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
